# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        working-directory: Solutions/Portals

    steps:
    - uses: actions/checkout@v4
    - uses: NuGet/setup-nuget@v2.0.0
      with:
        nuget-version: latest
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v2
      with:
        msbuild-architecture: x64
    - name: NuGet Restore
      run: nuget restore ${{ github.workspace }}\Solutions\Portals\Portals.sln
    - name: Run MSBuild
      working-directory: ${{ github.workspace }}\Solutions\Portals\ 
      run: msbuild Portals.sln /p:platform="Any CPU" /p:configuration=release /p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:PackageLocation=${{ runner.temp }}\\ /p:PrecompileBeforePublish=true /p:EnableUpdateable=false
    - uses: actions/upload-artifact@v4
      with:
        name: adx-portal
        path: ${{ runner.temp }}
       
    
